spring:
  application:
    name: dictionary-service
  datasource:
    url: jdbc:postgresql://localhost:61342/mydatabase
    username: myuser
    password: secret
  jpa:
    database: POSTGRESQL
    open-in-view: false
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    default-schema: postgres
    liquibase-schema: public
    user: myuser
    password: secret
    change-log: classpath:db/changelog/changelog.xml
